; Debug event popups: main/category/weapons/bracelets/scrolls/pots/meat1/meat2/meat3/flags.
; Native controller bytes and static English tiles are guarded/generated by
; debug_menus.py. ROM bank 254 $5000-$7EFF; temporary bank-5 WRAM
; $DA00-$DB21. The gate refuses nonzero scratch and clears it before returning.
DEF Scratch EQU $DA00
DEF SavedMap EQU $DA04
DEF ScratchEnd EQU $DB22
DEF LastCursor EQU Scratch + 2
DEF MenuKind EQU Scratch + 3 ; 0 = category, 1 = main, 2 = weapons, 3 = bracelets, 4 = scrolls, 5 = pots, 6 = meat1, 7 = meat2, 8 = meat3, 9 = flags

MACRO farcall
    ld a, \1
    ld hl, \2
    call $09AC
ENDM

SECTION "Debug category controller", ROMX[$5000], BANK[254]
    INCBIN "controller.bin"
    ASSERT @ <= $5140

; Keep constants in the existing controller/gate gap so the code helpers still
; end before the fixed private constructor at $5500.
SECTION "Debug menu identity records", ROMX[$5140], BANK[254]
EventIdentity: db $9F, $B4, $92, $4A
Choices: db 5, $40, $C6, 7, $C7, 7, $C8, 7, $C9, 7, $CA, 7
MainChoices: db 3, $40, $C5, 7, $E4, 7, $90, 7, 0, 0, 0, 0
WeaponsChoices: db 4, $40, $CB, 7, $CC, 7, $CD, 7, $CE, 7, 0, 0
BraceletsChoices: db 3, $40, $CF, 7, $D0, 7, $D1, 7, 0, 0, 0, 0
ScrollsChoices: db 4, $40, $D2, 7, $D3, 7, $D4, 7, $D5, 7, 0, 0
PotsChoices: db 2, $40, $D6, 7, $D7, 7, 0, 0, 0, 0, 0, 0
Meat1Choices: db 5, $40, $9F, 7, $D8, 7, $D9, 7, $DA, 7, $DB, 7
Meat2Choices: db 5, $40, $9F, 7, $DC, 7, $DD, 7, $DE, 7, $DF, 7
Meat3Choices: db 5, $40, $9F, 7, $E0, 7, $E1, 7, $E2, 7, $E3, 7
    ASSERT @ <= $51B0

; Geometry lives in the reserved constants/gate gap to keep helper code below $5500.
SECTION "Debug popup geometry", ROMX[$51B0], BANK[254]
Geometry:
    ; Call only with WRAM bank 5 selected. No persistent generic menu state.
    ld a, [MenuKind]
    cp 9
    ld bc, $090D
    ret z
    cp 8
    ld bc, $0B0B
    ret z
    cp 7
    ld bc, $0B0B
    ret z
    cp 6
    ld bc, $0B0B
    ret z
    cp 5
    ld bc, $0507
    ret z
    cp 4
    ld bc, $0908
    ret z
    and a
    ld bc, $0B0D
    ret z
    ld bc, $0709
    dec a
    ret z
    ld bc, $0908
    dec a
    ret z
    ld bc, $070A
    ret

    ASSERT @ <= $51F0

SECTION "Debug flag identity record", ROMX[$51F0], BANK[254]
FlagsChoices: db 4, $40, $E5, 7, $E6, 7, $E7, 7, $E8, 7, 0, 0
    ASSERT @ <= $5200

SECTION "Debug category gate", ROMX[$5200], BANK[254]
Gate::
    push bc
    push de
    ldh a, [$FF70]
    push af
    call IsDebugMenu
    jr nz, .native
    ld a, 5
    ldh [$FF70], a
    ld hl, Scratch
    ld bc, ScratchEnd - Scratch
.checkScratch
    ld a, [hli]
    and a
    jr nz, .native
    dec bc
    ld a, b
    or c
    jr nz, .checkScratch
    ld a, d
    ld [MenuKind], a
    pop af
    ldh [$FF70], a
    pop de
    pop bc
    call $501D
    push bc
    ldh a, [$FF70]
    push af
    ld a, 5
    ldh [$FF70], a
    ld hl, Scratch
    ld bc, ScratchEnd - Scratch
.clear
    xor a
    ld [hli], a
    dec bc
    ld a, b
    or c
    jr nz, .clear
    pop af
    ldh [$FF70], a
    pop bc
    ret
.native
    pop af
    ldh [$FF70], a
    pop de
    pop bc
    farcall $12, $401D
    ret

IsDebugMenu:
    ; Only the dungeon event, exact script position, flags and all twelve record
    ; bytes qualify. In particular, the cheat-controlled $C12F is irrelevant.
    ld a, [$C12B]
    and 1
    ret nz
    ld hl, $C3B4
    ld de, EventIdentity
    ld b, 4
    call Compare
    ret nz
    ld a, [$C3BF]
    cp $4B
    jr z, .page4b
    cp $4A
    ret nz
    ld a, [$C3BE]
    cp $BF
    jr z, .category
    cp $E4
    jr z, .weapons
    cp $A5
    ret nz
    ld de, MainChoices
    ld c, 1
    jr .record
.category
    ld de, Choices
    ld c, 0
    jr .record
.weapons
    ld de, WeaponsChoices
    ld c, 2
    jr .record
.page4b
    ; Exact positions only; other event choices on this page stay native.
    ld a, [$C3BE]
    cp $05
    jr z, .bracelets
    cp $22
    jr z, .scrolls
    cp $43
    jr z, .pots
    cp $5C
    jr z, .meat1
    cp $81
    jr z, .meat2
    cp $A6
    jr z, .meat3
    cp $CB
    ret nz
    ld de, FlagsChoices
    ld c, 9
    jr .record
.meat3
    ld de, Meat3Choices
    ld c, 8
    jr .record
.meat2
    ld de, Meat2Choices
    ld c, 7
    jr .record
.meat1
    ld de, Meat1Choices
    ld c, 6
    jr .record
.pots
    ld de, PotsChoices
    ld c, 5
    jr .record
.scrolls
    ld de, ScrollsChoices
    ld c, 4
    jr .record
.bracelets
    ld de, BraceletsChoices
    ld c, 3
.record
    ld hl, $FFB0
    ld b, 12
    call Compare
    ret nz
    ld d, c
    xor a
    ret
Compare:
    ld a, [de]
    cp [hl]
    ret nz
    inc de
    inc hl
    dec b
    jr nz, Compare
    ret


Constructor::
    ; Capture the whole covered rectangle before the native constructor.
    ; Native drawing still prepares its usual template, bitmap and bookkeeping.
    ldh a, [$FF70]
    push af
    ldh a, [$FF4F]
    push af
    ld a, 5
    ldh [$FF70], a
    call Origin
    ld a, l
    ld [Scratch], a
    ld a, h
    ld [Scratch + 1], a
    ld de, SavedMap
    call Geometry
.row
    push bc
    push hl
    ld b, c
.cell
    push bc
    push hl
    xor a
    ldh [$FF4F], a
    ld bc, 1
    call $0A6B
    pop hl
    push hl
    ld a, 1
    ldh [$FF4F], a
    ld bc, 1
    call $0A6B
    pop hl
    call NextCell
    pop bc
    dec b
    jr nz, .cell
    pop hl
    call NextRow
    pop bc
    dec b
    jr nz, .row
    pop af
    ldh [$FF4F], a
    pop af
    ldh [$FF70], a
    jp NativeConstructor

CursorInit::
    farcall $10, $5CAF
    jp Paint
CursorMove::
    ; Native selection/repeat/sound logic, with its cursor drawing restricted
    ; to the cached WRAM bitmap. Never touch visible glyph tiles while moving.
    call NativeMove
    jp MoveCursorCells

Paint:
    push af
    push bc
    push de
    push hl
    ldh a, [$FF70]
    push af
    ldh a, [$FF4F]
    push af
    xor a
    ldh [$FF4F], a
    ld a, 5
    ldh [$FF70], a
    ld hl, Tiles
    ld a, [MenuKind]
    and a
    jr z, .tiles
    ld hl, MainTiles
    dec a
    jr z, .tiles
    ld hl, WeaponsTiles
    dec a
    jr z, .tiles
    ld hl, BraceletsTiles
    dec a
    jr z, .tiles
    ld hl, ScrollsTiles
    dec a
    jr z, .tiles
    ld hl, PotsTiles
    dec a
    jr z, .tiles
    ld hl, Meat1Tiles
    dec a
    jr z, .tiles
    ld hl, Meat2Tiles
    dec a
    jr z, .tiles
    ld hl, Meat3Tiles
    dec a
    jr z, .tiles
    ld hl, FlagsTiles
.tiles
    ld de, $8900
    ld bc, $0310
    call $0A6B
    call Destination
    ld hl, Frame
    ld a, [MenuKind]
    and a
    jr z, .frame
    ld hl, MainFrame
    dec a
    jr z, .frame
    ld hl, WeaponsFrame
    dec a
    jr z, .frame
    ld hl, BraceletsFrame
    dec a
    jr z, .frame
    ld hl, ScrollsFrame
    dec a
    jr z, .frame
    ld hl, PotsFrame
    dec a
    jr z, .frame
    ld hl, Meat1Frame
    dec a
    jr z, .frame
    ld hl, Meat2Frame
    dec a
    jr z, .frame
    ld hl, Meat3Frame
    dec a
    jr z, .frame
    ld hl, FlagsFrame
.frame
    call Geometry
    call CopyMap
    call Destination
    ld h, d
    ld l, e
    call NextRow
    call NextCell
    ld a, [$C14F]
    ld [LastCursor], a
    and a
    jr z, .cursor
    ld b, a
.cursorRow
    call NextRow
    call NextRow
    dec b
    jr nz, .cursorRow
.cursor
    ld d, h
    ld e, l
    xor a
    ldh [$FF4F], a
    ld hl, CursorTile
    ld bc, 1
    call $0A6B
    pop af
    ldh [$FF4F], a
    pop af
    ldh [$FF70], a
    pop hl
    pop de
    pop bc
    pop af
    ret
CursorTile: db $91

MoveCursorCells:
    push af
    push bc
    push de
    push hl
    ldh a, [$FF70]
    push af
    ld a, 5
    ldh [$FF70], a
    ld a, [LastCursor]
    ld b, a
    ld a, [$C14F]
    cp b
    jr z, .done
    ld [LastCursor], a
    push af
    ld a, b
    call CursorAddress
    pop af
    push hl
    call CursorAddress
    pop de
    ldh a, [$FF4F]
    push af
    xor a
    ldh [$FF4F], a
.wait
    ldh a, [$FF40]
    and $80
    jr z, .lcdOff
    ldh a, [$FF44]
    cp 144
    jr c, .wait
    cp 152
    jr nc, .wait
    di
    ; Recheck after disabling interrupts: an IRQ between the first check and
    ; DI must not let these two writes cross into the next visible frame.
    ldh a, [$FF44]
    cp 144
    jr c, .retry
    cp 152
    jr c, .write
.retry
    ei
    jr .wait
.lcdOff
    di
.write
    ld a, $90
    ld [de], a
    ld [hl], $91
    ei
    pop af
    ldh [$FF4F], a
.done
    pop af
    ldh [$FF70], a
    pop hl
    pop de
    pop bc
    pop af
    ret

CursorAddress:
    push af
    call Destination
    ld h, d
    ld l, e
    call NextRow
    call NextCell
    pop af
    and a
    ret z
    ld b, a
.row
    call NextRow
    call NextRow
    dec b
    jr nz, .row
    ret

Restore::
    ; Retire every visible private map cell BEFORE replacing its shared glyph
    ; tiles with the native cache. Reversing this order flashes aliased arrows.
    ldh a, [$FF70]
    push af
    ldh a, [$FF4F]
    push af
    ld a, 5
    ldh [$FF70], a
    call Destination
    ld hl, SavedMap
    call Geometry
    call CopyMap
    ld a, 7
    ldh [$FF70], a
    xor a
    ldh [$FF4F], a
    ld hl, $D900
    ld de, $8900
    ld bc, $0310
    call $0A6B
    pop af
    ldh [$FF4F], a
    pop af
    ldh [$FF70], a
    farcall $B9, $49EE
    ret

Destination:
    ld a, [Scratch]
    ld e, a
    ld a, [Scratch + 1]
    ld d, a
    ret
Origin:
    ; Same SCX/SCY-derived origin as native bank 3 $6A65.
    ldh a, [$FF42]
    swap a
    inc a
    and $0F
    ld hl, $0040
    call $0C20
    ldh a, [$FF43]
    swap a
    inc a
    and $0F
    add a
    call $0BB9
    ld de, $9800
    add hl, de
    ret
    ASSERT @ <= $5500

SECTION "Debug popup hidden native construction", ROMX[$5500], BANK[254]
NativeConstructor:: INCBIN "constructor.bin"
NativeLayoutData:: INCBIN "native-layout.bin"
    ASSERT @ <= $55D0

; Unchanged toroidal BG stepping, relocated into the constructor's spare tail.
SECTION "Debug popup map stepping", ROMX[$55D0], BANK[254]
NextCell:
    ld a, l
    and $E0
    ld c, a
    ld a, l
    inc a
    and $1F
    or c
    ld l, a
    ret
NextRow:
    ld a, l
    add $20
    ld l, a
    ret nc
    inc h
    ld a, h
    cp $9C
    ret nz
    ld h, $98
    ret
    ASSERT @ <= $5600

SECTION "Debug category cached navigation", ROMX[$5600], BANK[254]
NativeMove:: INCBIN "navigation.bin"
CacheNativeCursors:: INCBIN "native-cursors.bin"

CacheGlyph::
    ; Same wrapper as native 17:$477F, with mode $05 instead of $01.
    ; Bit 2 suppresses the compositor's VRAM upload at 0:$39B3, preserving
    ; every native cached cursor edit for byte-identical exit restoration.
    ld a, [$C4DA]
    push af
    ld a, $05
    ld [$C4DA], a
    ld hl, $C4D6
    ld [hl], e
    inc hl
    ld [hl], d
    ld a, c
    ld de, $002E
    and a
    jr nz, .glyph
    ld de, $0024
.glyph
    farcall 3, $6EDD
    pop af
    ld [$C4DA], a
    ret
NavigationGraph:: INCBIN "navigation-graph.bin"

CopyMap:
    ; HL = interleaved tile/attribute source; DE = BG destination; B/C = H/W.
    ; Keep the writes local to this popup. Native $0AEA can lose a cell if an
    ; IRQ runs after its STAT check and returns during PPU transfer mode.
.row
    push bc
    push de
    ld b, c
.cell
    push bc
    ld a, [hli]
    ld c, a
    ld a, [hli]
    ld b, a
    call WriteMapCell
    push hl
    ld h, d
    ld l, e
    call NextCell
    ld d, h
    ld e, l
    pop hl
    pop bc
    dec b
    jr nz, .cell
    pop de
    push hl
    ld h, d
    ld l, e
    call NextRow
    ld d, h
    ld e, l
    pop hl
    pop bc
    dec b
    jr nz, .row
    ret

WriteMapCell:
    ldh a, [$FF40]
    and $80
    jr z, .lcdOff
.wait
    ldh a, [$FF41]
    and 2
    jr nz, .wait
    di
    ; Recheck with IRQs disabled before either plane is written. The pair is
    ; short enough to finish before mode 3 even at the very end of HBlank.
    ldh a, [$FF41]
    and 2
    jr nz, .retry
.write
    xor a
    ldh [$FF4F], a
    ld a, c
    ld [de], a
    ld a, 1
    ldh [$FF4F], a
    ld a, b
    ld [de], a
    ei
    ret
.retry
    ei
    jr .wait
.lcdOff
    di
    jr .write
    ASSERT @ <= $5800

SECTION "Debug category tiles", ROMX[$5800], BANK[254]
Tiles: INCBIN "tiles.bin"
Frame: INCBIN "frame.bin"
MainTiles: INCBIN "main-tiles.bin"
MainFrame: INCBIN "main-frame.bin"
    ASSERT @ <= $6000

SECTION "Debug Weapons-Shields tiles", ROMX[$6000], BANK[254]
WeaponsTiles: INCBIN "weapons-tiles.bin"
WeaponsFrame: INCBIN "weapons-frame.bin"
    ASSERT @ <= $6400

SECTION "Debug Bracelets-Grass tiles", ROMX[$6400], BANK[254]
BraceletsTiles: INCBIN "bracelets-tiles.bin"
BraceletsFrame: INCBIN "bracelets-frame.bin"
    ASSERT @ <= $6800

SECTION "Debug Scrolls-Staves tiles", ROMX[$6800], BANK[254]
ScrollsTiles: INCBIN "scrolls-tiles.bin"
ScrollsFrame: INCBIN "scrolls-frame.bin"
    ASSERT @ <= $6BA0

; Keep all existing 49-tile payloads, but remove inter-block padding so the
; final menu fits the same audited reservation without borrowing more memory.
SECTION "Debug Pots Meat and Flag tiles", ROMX[$6BA0], BANK[254]
PotsTiles: INCBIN "pots-tiles.bin"
PotsFrame: INCBIN "pots-frame.bin"
Meat1Tiles: INCBIN "meat1-tiles.bin"
Meat1Frame: INCBIN "meat1-frame.bin"
Meat2Tiles: INCBIN "meat2-tiles.bin"
Meat2Frame: INCBIN "meat2-frame.bin"
Meat3Tiles: INCBIN "meat3-tiles.bin"
Meat3Frame: INCBIN "meat3-frame.bin"
FlagsTiles: INCBIN "flags-tiles.bin"
FlagsFrame: INCBIN "flags-frame.bin"
    ASSERT @ <= $7F00
