#!/usr/bin/env python3
"""Convert Shiren GB2 passwords between Japanese and this patch's English alphabet.

No ROM or third-party packages are required. Conversion preserves the original
six-bit symbols, including unused padding bits; it never regenerates a packet.
"""
import argparse
import json
from pathlib import Path
import sys
import unicodedata

import rescue_password as protocol


ROOT = Path(__file__).resolve().parents[1]
MISSION_PATH = ROOT / "data" / "special_rescue_missions.json"
KINDS = {9: "training", 12: "thank_you", 13: "sos", 15: "revival"}
# Explicit shared Unicode White_Space set (rather than Python/JS's different \s).
WHITESPACE = "\t\n\v\f\r \u0085\u00a0\u1680" + "".join(
    chr(value) for value in range(0x2000, 0x200B)
) + "\u2028\u2029\u202f\u205f\u3000"


def normalize(text):
    """Accept pasted whitespace, decomposed kana, and full/half-width input."""
    if not isinstance(text, str):
        raise ValueError("Password must be text.")
    text = unicodedata.normalize("NFKC", text)
    return "".join(
        chr(ord(character) - 0x60) if "\u30a1" <= character <= "\u30f6" else character
        for character in text if character not in WHITESPACE
    )


def convert(text, to="english"):
    """Validate a packet and map its symbols without changing its payload."""
    if to not in ("english", "japanese"):
        raise ValueError("Output language must be english or japanese.")
    text = normalize(text)
    if not text:
        raise ValueError("Enter a password first.")
    source = "japanese" if to == "english" else "english"
    alphabet = protocol.NATIVE_ALPHABET if source == "japanese" else protocol.LOCALIZED_ALPHABET
    for position, character in enumerate(text, 1):
        if character not in alphabet:
            raise ValueError(
                "Character %r at position %d is not in the %s rescue alphabet. Check the conversion direction."
                % (character, position, source.title())
            )
    if len(text) not in KINDS:
        raise ValueError(
            "Password has %d symbols. Expected 9 (Training), 12 (Thank-You), 13 (SOS), or 15 (Revival)."
            % len(text)
        )
    values = [alphabet.index(character) for character in text]
    native = bytes(protocol.NATIVE_ALPHABET_CODES[value] for value in values)
    payload = protocol.decode_password(native)
    result = {
        "japanese": "".join(protocol.NATIVE_ALPHABET[value] for value in values),
        "english": protocol.localize_password(native),
        "kind": KINDS[len(text)],
        "length": len(text),
        "payload_hex": payload.hex(),
    }
    return result


def mission_data():
    data = json.loads(MISSION_PATH.read_text(encoding="utf-8"))
    for mission in data["missions"]:
        converted = convert(mission["japanese"])
        if any(converted[key] != mission[key] for key in ("english", "payload_hex")):
            raise ValueError("Published mission mapping changed: " + mission["id"])
        sos = protocol.SOSPayload.from_payload(bytes.fromhex(converted["payload_hex"]))
        if (sos.dungeon_id, sos.internal_floor) != (mission["dungeon_id"], mission["floor"]):
            raise ValueError("Published mission destination changed: " + mission["id"])
    return data


def web_data():
    """Generate the browser's data from the ROM presentation's source of truth."""
    data = mission_data()
    data.update({
        "native_alphabet": protocol.NATIVE_ALPHABET,
        "english_alphabet": protocol.LOCALIZED_ALPHABET,
        "whitespace": WHITESPACE,
        "kinds": KINDS,
        "payload_lengths": protocol.PAYLOAD_LENGTHS,
    })
    return (
        "// Generated by tools/rescue_converter.py --export-web-data. Do not edit.\n"
        "(function (root) {\n  const data = "
        + json.dumps(data, ensure_ascii=True, indent=2)
        + ";\n  if (typeof module === 'object' && module.exports) module.exports = data;\n"
        "  else root.RescuePasswordData = data;\n})(globalThis);\n"
    )


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("password", nargs="?", help="password, or - to read standard input")
    parser.add_argument("--to", choices=("english", "japanese"), default="english")
    parser.add_argument("--json", action="store_true", help="include packet kind and decoded payload")
    parser.add_argument("--export-web-data", metavar="PATH", type=Path,
                        help="write browser data instead of converting a password")
    args = parser.parse_args(argv)
    if args.export_web_data is not None and args.password is not None:
        parser.error("choose either a password or --export-web-data")
    if args.export_web_data is None and args.password is None:
        parser.error("provide a password (or - for standard input)")
    try:
        if args.export_web_data is not None:
            args.export_web_data.parent.mkdir(parents=True, exist_ok=True)
            args.export_web_data.write_text(web_data(), encoding="utf-8")
        else:
            text = sys.stdin.read() if args.password == "-" else args.password
            result = convert(text, args.to)
            print(json.dumps(result, ensure_ascii=False, indent=2) if args.json else result[args.to])
    except (OSError, ValueError) as error:
        parser.exit(1, "error: %s\n" % error)
    return 0


if __name__ == "__main__":
    sys.exit(main())
